### ISSUE TITLE
请问一下作者是如何实现文字点选这个操作的，模拟浏览器吗

### ISSUE THREAD

**Issue by STX5** [zhiying8710/geetest_crack#9]
最近在搞网易易盾的文字点选验证码，能够获得正确的点击坐标。但是就算点选操作无误也过不了验证码，怀疑现在的反爬服务可以根据模拟浏览器的特征进行拦截。

**Comment by zhiying8710** [comment]
模拟浏览器

**Comment by zijiwork** [comment]
能提供简单的demo供学习参考嘛？

**Comment by zhiying8710** [comment]
https://github.com/miyakogi/pyppeteer
